[package]
name = "logram"
version = "1.0.0"
edition = "2018"
authors = ["Maxim Lisw <ralvke@gmail.com>"]
description = "Push logs updates to Telegram"
repository = "https://github.com/Ralvke/logram"
readme = "README.md"
keywords = ["telegram", "bot", "log"]
license = "MIT"

[badges]
travis-ci = { repository = "Ralvke/logram", branch = "master" }

[dependencies]
