[package]
name = "logram"
version = "0.1.0"
authors = ["Maxim Lis <ralvke@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
serde_json = "1.0"
reqwest = "0.8"
url = "1.5"
notify = "4.0"
regex = "0.2"